version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/repo
    steps:
      - checkout
      # install dependencies
      - run:
          name: Install Server Dependencies
          command: npm install
      - run: 
          name: Install Client Dependencies
          command: cd client && npm install
      - run: 
          name: Test Build
          command: cd client && npm run build
      # ignoring tests for now
      # - run:
      #     name: Run tests
      #     command: npm run test

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          app-name: $HEROKU_PRODUCTION_APP_NAME
          requires:
            - build
          filters:
            branches:
              only: main
              
